#### CI pipeline
name: CI

on:
  push:
    branches: 
      - main
    paths:
      - 'cart/**'

env:
  DOCKER_REPO: robot-shop-cart

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: ./robot_shop/cart
        run: npm install

      - name: Build
        run: npm run build

      - name: Docker build
        run: docker build -t ${{ secrets.DOCKER_USER || 'default-user' }}/${{ env.DOCKER_REPO }}:${{ github.run_id }} .

      - name: Scan Docker image
        run: docker scan ${{ secrets.DOCKER_USER || 'default-user' }}/${{ env.DOCKER_REPO }}:${{ github.run_id }}

      - name: Docker push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD || 'default-password' }}" | docker login -u "${{ secrets.DOCKER_USER || 'sandhya0593' }}" --password-stdin
          docker push ${{ secrets.DOCKER_USER || 'sandhya0593' }}/${{ env.DOCKER_REPO }}:${{ github.run_id }}

      - name: Update Kubernetes manifest
        run: |
          sed -i 's|${{ secrets.DOCKER_USER || "sandhya0593" }}/${{ env.DOCKER_REPO }}:latest|${{ secrets.DOCKER_USER || "default-user" }}/${{ env.DOCKER_REPO }}:${{ github.run_id }}|g' k8s/cart/deployment.yaml
