name: CI Pipeline

on:
  push:
    branches:
      - main
    paths: 
      - 'cart/**'


jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java for SonarQube analysis
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # Step 3: SonarQube analysis (assuming SonarQube is configured)
      # - name: SonarQube Scan
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   run: |
      #     ./gradlew sonarqube \
      #       -Dsonar.projectKey=your_project_key \
      #       -Dsonar.host.url=https://sonarcloud.io

      # Step 4: Build Docker image with unique tag
      - name: Build Docker image
        run: |
          IMAGE_TAG=$(date +%s)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t sandhya0593/robot-shop-cart:$IMAGE_TAG .

      # Step 5: Install Trivy for scanning
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

      # Step 6: Scan Docker image
      - name: Scan Docker image
        run: |
          trivy image sandhya0593/robot-shop-cart:${{ env.IMAGE_TAG }}

      # Step 7: Push Docker image to registry
      - name: Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push sandhya0593/robot-shop-cart:${{ env.IMAGE_TAG }}

      # Step 8: Update Kubernetes deployment file
      - name: Update Kubernetes deployment
        run: |
          sed -i "s|image: sandhya0593/robot-shop-cart:.*|image: sandhya0593/srobot-shop-cart:${{ env.IMAGE_TAG }}|" k8s/deployment.yml
          